
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.PackageManagement
{
	public partial class ManagePackagesDialog
	{
		private global::Gtk.Button buttonClose;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.PackageManagement.ManagePackagesDialog
			this.Name = "MonoDevelop.PackageManagement.ManagePackagesDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Manage Packages");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 640;
			this.DefaultHeight = 480;
			this.DestroyWithParent = true;
			// Internal child MonoDevelop.PackageManagement.ManagePackagesDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "mainVBox";
			w1.BorderWidth = ((uint)(2));
			// Internal child MonoDevelop.PackageManagement.ManagePackagesDialog.ActionArea
			global::Gtk.HButtonBox w2 = this.ActionArea;
			w2.Name = "buttonArea";
			w2.Spacing = 10;
			w2.BorderWidth = ((uint)(5));
			w2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child buttonArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.CanDefault = true;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseStock = true;
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = "gtk-close";
			this.AddActionWidget (this.buttonClose, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w2 [this.buttonClose]));
			w3.Expand = false;
			w3.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
