
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.PackageManagement
{
	public partial class LicenseAcceptanceDialog
	{
		private global::Gtk.HBox subTitleHBoxForSinglePackage;
		private global::Gtk.Label subTitleLabelForSinglePackage;
		private global::Gtk.HBox subTitleHBoxForMultiplePackages;
		private global::Gtk.Label subTitleLabelForMultiplePackages;
		private global::Gtk.VBox packagesVBox;
		private global::Gtk.Label fillerLabel;
		private global::Gtk.HBox bottomMessageHBox;
		private global::Gtk.Label mainMessageLabel;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.PackageManagement.LicenseAcceptanceDialog
			this.Name = "MonoDevelop.PackageManagement.LicenseAcceptanceDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("License Agreements");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			// Internal child MonoDevelop.PackageManagement.LicenseAcceptanceDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "mainVBox";
			w1.BorderWidth = ((uint)(2));
			// Container child mainVBox.Gtk.Box+BoxChild
			this.subTitleHBoxForSinglePackage = new global::Gtk.HBox ();
			this.subTitleHBoxForSinglePackage.Name = "subTitleHBoxForSinglePackage";
			this.subTitleHBoxForSinglePackage.Spacing = 6;
			// Container child subTitleHBoxForSinglePackage.Gtk.Box+BoxChild
			this.subTitleLabelForSinglePackage = new global::Gtk.Label ();
			this.subTitleLabelForSinglePackage.Name = "subTitleLabelForSinglePackage";
			this.subTitleLabelForSinglePackage.LabelProp = global::Mono.Unix.Catalog.GetString ("The following package requires a click-to-accept license:");
			this.subTitleHBoxForSinglePackage.Add (this.subTitleLabelForSinglePackage);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.subTitleHBoxForSinglePackage [this.subTitleLabelForSinglePackage]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w1.Add (this.subTitleHBoxForSinglePackage);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.subTitleHBoxForSinglePackage]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.subTitleHBoxForMultiplePackages = new global::Gtk.HBox ();
			this.subTitleHBoxForMultiplePackages.Name = "subTitleHBoxForMultiplePackages";
			this.subTitleHBoxForMultiplePackages.Spacing = 6;
			// Container child subTitleHBoxForMultiplePackages.Gtk.Box+BoxChild
			this.subTitleLabelForMultiplePackages = new global::Gtk.Label ();
			this.subTitleLabelForMultiplePackages.Name = "subTitleLabelForMultiplePackages";
			this.subTitleLabelForMultiplePackages.LabelProp = global::Mono.Unix.Catalog.GetString ("The following packages require a click-to-accept license:");
			this.subTitleHBoxForMultiplePackages.Add (this.subTitleLabelForMultiplePackages);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.subTitleHBoxForMultiplePackages [this.subTitleLabelForMultiplePackages]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add (this.subTitleHBoxForMultiplePackages);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.subTitleHBoxForMultiplePackages]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.packagesVBox = new global::Gtk.VBox ();
			this.packagesVBox.Name = "packagesVBox";
			this.packagesVBox.Spacing = 6;
			w1.Add (this.packagesVBox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.packagesVBox]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Padding = ((uint)(3));
			// Container child mainVBox.Gtk.Box+BoxChild
			this.fillerLabel = new global::Gtk.Label ();
			this.fillerLabel.Name = "fillerLabel";
			w1.Add (this.fillerLabel);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.fillerLabel]));
			w7.Position = 3;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.bottomMessageHBox = new global::Gtk.HBox ();
			this.bottomMessageHBox.Name = "bottomMessageHBox";
			this.bottomMessageHBox.Spacing = 6;
			// Container child bottomMessageHBox.Gtk.Box+BoxChild
			this.mainMessageLabel = new global::Gtk.Label ();
			this.mainMessageLabel.Name = "mainMessageLabel";
			this.mainMessageLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("By clicking \"OK\" you agree to the license terms for the packages listed above.\nIf" +
				" you do not agree to the license terms click \"Cancel\".");
			this.bottomMessageHBox.Add (this.mainMessageLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.bottomMessageHBox [this.mainMessageLabel]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			w1.Add (this.bottomMessageHBox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.bottomMessageHBox]));
			w9.Position = 4;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child MonoDevelop.PackageManagement.LicenseAcceptanceDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "mainButtonArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child mainButtonArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonCancel]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child mainButtonArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonOk]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 447;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
